### ISSUE TITLE
Build failure with GHC 9.4.5

### ISSUE THREAD

**Issue by andreasabel** [hasufell/streamly-yaml#4]
I came here investigating the impact of 
- https://github.com/pcapriotti/optparse-applicative/issues/481

but I cannot build the project, not from the repo nor from the released version:
```
$ cabal get yaml-streamly
$ cd yaml-streamly-0.12.2/
$ cabal build -w ghc-9.4.5

Build profile: -w ghc-9.4.5 -O1
In order, the following will be built (use -v for more details):
 - libyaml-streamly-0.2.1 (lib) (requires download & build)
 - yaml-streamly-0.12.2 (lib) (first run)
...
Building library for libyaml-streamly-0.2.1..
[1 of 2] Compiling Paths_libyaml_streamly ( dist/build/autogen/Paths_libyaml_streamly.hs, dist/build/Paths_libyaml_streamly.o, dist/build/Paths_libyaml_streamly.dyn_o )
[2 of 2] Compiling Text.Libyaml     ( src/Text/Libyaml.hs, dist/build/Text/Libyaml.o, dist/build/Text/Libyaml.dyn_o )

src/Text/Libyaml.hs:80:1: error:
    Could not load module ‘Streamly.Internal.Data.Stream.StreamD.Type’
    It is a member of the hidden package ‘streamly-core-0.1.0’.
    Perhaps you need to add ‘streamly-core’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
80 | import qualified Streamly.Internal.Data.Stream.StreamD.Type as D
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by hasufell** [comment]
The module `Streamly.Internal.Data.Stream.StreamD.Type` was dropped from streamly-0.9.0.

@harendra-kumar what is the upgrade path?

**Comment by harendra-kumar** [comment]
It is not dropped, it is available in the `streamly-core` package. For other upgrade related info see https://streamly.composewell.com/streamly-0.9.0/User/ProjectRelated/Upgrading.html .

**Comment by andreasabel** [comment]
`cabal build all -w ghc-9.4.5 -c 'streamly < 0.9'` succeeds, so maybe adding bound `streamly < 0.9` to the hackage releases would be the right course of action?

**Comment by hasufell** [comment]
@andreasabel that seems reasonable. 

@Bodigrim can you make that change via revision? I still don't have a laptop.

**Comment by andreasabel** [comment]
I made revisions adding `streamly < 0.9` and `optparse-applicative < 0.18`.
